### ISSUE TITLE
Exception on unsigning with RS256

### ISSUE THREAD

**Issue by metametadata** [funcool/buddy-sign#43]
See minimal project: https://github.com/metametadata/buddy-rs256-issue

In a nutshell, this code:

```clj
; example data is taken from https://jwt.io/
(jws/unsign "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.EkN-DOsnsuRjRO6BxXemmJDm3HbxrbRzXglbN2S4sOkopdU4IsDxTI8jO19W_A4K8ZPJijNLis4EZsHeY559a4DFOd50_OqgHGuERTqYZyuhtF39yxJPAjUESwxk2J5k_4zM3O-vtd1Ghyo4IbqKKSy6J9mTniYJPenn5-HIirE"
            "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDdlatRjRjogo3WojgGHFHYLugdUWAY9iR3fy4arWNA1KoS8kVw33cJibXr8bvwUAUparCwlvdbH6dvEOfou0/gCFQsHUfQrSDv+MuSUMAe8jzKE4qW+jK+xQU9a03GUnKHkkle+Q0pX/g6jXZ7r1/xAK5Do2kQ+X5xK9cipRgEKwIDAQAB\n-----END PUBLIC KEY-----"
            {:alg :rs256})
```

causes the exception:

```
Hello, World!
Exception in thread "main" java.lang.IllegalArgumentException: No matching method found: initVerify for class java.security.Signature$Delegate, compiling:(/private/var/folders/7_/mhk7y9952n972b6kgt7_8l700000gn/T/form-init829514710048949323.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No matching method found: initVerify for class java.security.Signature$Delegate
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:80)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at buddy.core.dsa$eval737$fn__738.invoke(dsa.clj:72)
	at buddy.core.dsa$eval641$fn__672$G__628__679.invoke(dsa.clj:43)
	at buddy.core.dsa$verify.invokeStatic(dsa.clj:161)
	at buddy.core.dsa$verify.invoke(dsa.clj:158)
	at buddy.sign.jws$fn__1775.invokeStatic(jws.clj:41)
	at buddy.sign.jws$fn__1775.invoke(jws.clj:30)
	at buddy.sign.jws$verify_signature.invokeStatic(jws.clj:95)
	at buddy.sign.jws$verify_signature.invoke(jws.clj:87)
	at buddy.sign.jws$unsign.invokeStatic(jws.clj:133)
	at buddy.sign.jws$unsign.invoke(jws.clj:127)
	at buddy_rs256_issue.core$_main.invokeStatic(core.clj:6)
	at buddy_rs256_issue.core$_main.doInvoke(core.clj:4)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invokeStatic(form-init829514710048949323.clj:1)
	at user$eval5.invoke(form-init829514710048949323.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
```

**Comment by metametadata** [comment]
I've figured this out, I need to convert the string into public key object first using `str->public-key`:

```clj
(:require [buddy.sign.jws :as jws]
            [buddy.core.keys :as buddy-keys])
,,,
(jws/unsign "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.EkN-DOsnsuRjRO6BxXemmJDm3HbxrbRzXglbN2S4sOkopdU4IsDxTI8jO19W_A4K8ZPJijNLis4EZsHeY559a4DFOd50_OqgHGuERTqYZyuhtF39yxJPAjUESwxk2J5k_4zM3O-vtd1Ghyo4IbqKKSy6J9mTniYJPenn5-HIirE"
              (buddy-keys/str->public-key "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDdlatRjRjogo3WojgGHFHYLugdUWAY9iR3fy4arWNA1KoS8kVw33cJibXr8bvwUAUparCwlvdbH6dvEOfou0/gCFQsHUfQrSDv+MuSUMAe8jzKE4qW+jK+xQU9a03GUnKHkkle+Q0pX/g6jXZ7r1/xAK5Do2kQ+X5xK9cipRgEKwIDAQAB\n-----END PUBLIC KEY-----")
              {:alg :rs256})
```

[The example](https://funcool.github.io/buddy-sign/latest/#jws) uses the string secret and it was not intuitive that another algorithm may need the secret of another type (in this case it's `org.bouncycastle.jcajce.provider.asymmetric.rsa.BCRSAPublicKey`).

**Comment by ignorabilis** [comment]
This should be part of the docs, took me a few hours to figure out that I need to convert the string to a public key and only then to unsign the token; as pointed above it is not evident that for different algorithms the type of the secret can be different.
